try { __ez.fads.incontentSticky={divsDisabled:[],loaded:true,isIncontentStickyOff:false,log:__ez.fads.log,ezoicFixedClasses:['ezoic-ad','ezmob-footer','ez-sidebar-wall','ez-sidebar-wall-ad','ez-video-container','ezoic-floating-bottom'],init:function(){if(document.readyState==='interactive'||document.readyState==='complete'){__ez.fads.incontentSticky.CheckIncontentSticky(false);}else{window.addEventListener('load',function(){__ez.fads.incontentSticky.CheckIncontentSticky(false)});}
document.addEventListener('DOMContentLoaded',function(){__ez.fads.incontentSticky.CheckIncontentSticky(true)});setInterval(function(){__ez.fads.incontentSticky.ResizeAlteredElements();},5000);},reset:function(){this.divsDisabled=[];this.isIncontentStickyOff=false;},isAllowedSticky:function(parentElement){const descendants=parentElement.children;for(const element of descendants){if(this.isAllowedFixed(element.classList)){continue;}
var style=window.getComputedStyle(element);if(style.position==='fixed'&&this.isHidden(element,style)===false){return false;}}
return true;},isAllowedFixed:function(classList){for(var i=0;i<classList.length;i++){var className=classList[i];if(this.ezoicFixedClasses.indexOf(className)>-1){return true;}}
return false;},isHidden:function(element,style){return style.display==='none'||style.visibility==='hidden'||style.opacity==='0'||style.height==='0px'||style.width==='0px'||style.maxHeight==='0px'||style.maxWidth==='0px'||this.isElementOffScreen(element);},isElementOffScreen:function(elem){var rect=elem.getBoundingClientRect();return(rect.top<0||rect.left<0||rect.bottom>(window.innerHeight||document.documentElement.clientHeight)||rect.right>(window.innerWidth||document.documentElement.clientWidth));},removeSticky:function(elem){if(elem&&elem.hasAttribute('ezaw')){elem.style.minHeight=elem.getAttribute('ezaw');}
if(elem&&elem.hasAttribute('ezah')){var ezahValue=elem.getAttribute('ezah');}else if(elem.style.height){var ezahValue=elem.style.height.replace('px','');}
if(ezahValue){ezahValue=parseInt(ezahValue)+30;elem.style.minHeight=ezahValue+"px";elem.parentElement.style.minHeight=ezahValue+"px";}
if(elem.id&&typeof __ez.fads.adLoadGAM.SetTargeting=='function'){__ez.fads.callLibrary('adLoadGAM','SetTargeting',[elem.id,'sticky','0']);__ez.fads.callLibrary('adLoadGAM','SetTargeting',[elem.id,'icsticky','0']);}
__ez.fads.log&&__ez.fads.log("incontentsticky:: removed incontent sticky",elem);this.removeIncontentStyling(elem);},adjustOverflowProperty:function(parent,ad_div,propName,propVal){if(!this.isAllowedSticky(parent)){this.isIncontentStickyOff=true;this.removeSticky(ad_div);}else{parent.style.setProperty(propName,propVal,'important');}},checkParentStyles:function(elem){var elemWidth=elem.offsetWidth;if(elem.style.maxWidth){elemWidth=elem.style.maxWidth.replace('px','');}
if(elem.parentElement.offsetWidth<elemWidth){this.removeIncontentStyling(elem);}},removeIncontentStyling:function(elem){elem.parentElement.style.setProperty("background","none","important");elem.parentElement.style.setProperty("border","none","important");if(elem.classList){elem.classList.remove('ezads-sticky-intradiv');}
elem.style.top="0px";},checkTopFixed:function(){var topHt=this.getTopFixedHeight();if(topHt>0){var elements=document.querySelectorAll('.ezads-sticky-intradiv');for(var i=0;i<elements.length;i++){if((' '+elements[i].parentNode.className+' ').indexOf('ezads-sticky-intradiv')==-1){elements[i].style.setProperty('padding-top',topHt+"px","important");elements[i].style.setProperty('margin-top',"-"+topHt+"px","important");}}}},getTopFixedHeight:function(){if(this.isIncontentStickyOff==true){return 0;}
var topFixedHeight=0;var allElements=document.querySelectorAll('*');for(let i=0;i<allElements.length;i++){var element=allElements[i];var style=window.getComputedStyle(element);if((style.position==='fixed'||style.position==='sticky')&&this.isHidden(element,style)===false){var topInt=parseInt(style.top);if(style.position==='sticky'){topInt=element.getBoundingClientRect().top;}
if(topInt<=5&&element.offsetHeight>topFixedHeight){topFixedHeight=element.offsetHeight;}}}
if(topFixedHeight>124){if(topFixedHeight>200){topFixedHeight=0;}else{topFixedHeight=124;}}
return topFixedHeight;},ResizeAlteredElements:function(){var elements=document.querySelectorAll('[data-ezoic-incontent-sticky]');for(var i=0;i<elements.length;i++){var element=elements[i];var computedStyle=getComputedStyle(element);var overY=computedStyle.overflowY;if(overY.indexOf('clip')!==-1){element.style.setProperty('overflow','hidden','important');if(element.offsetHeight>element.style.minHeight.replace('px','')){element.style.setProperty('min-height',element.offsetHeight+'px','important');}
element.style.setProperty('overflow','clip','important');}}},CheckIncontentSticky:function(retry){try{var elements=document.querySelectorAll('.ezads-sticky-intradiv');for(var i=0;i<elements.length;i++){var ad_div=elements[i];this.checkParentStyles(ad_div);if(this.isIncontentStickyOff==true){this.removeSticky(ad_div);continue;}
var parent=elements[i].parentElement;while(parent){if(parent.nodeType===1&&parent.tagName&&parent.tagName.toLowerCase()==='html'){continue;}
var computedStyle=getComputedStyle(parent);var overY=computedStyle.overflowY;var overflowClass="";if(['hidden','scroll','auto'].includes(overY)){overflowClass="clip";if(['scroll','auto'].includes(overY)){overflowClass="visible";}
this.adjustOverflowProperty(parent,ad_div,'overflow-y',overflowClass);var dataMsg='overflow changed to clip from hidden';if(parent.offsetHeight>parent.style.minHeight.replace('px','')){this.adjustOverflowProperty(parent,ad_div,'min-height',parent.offsetHeight+'px');dataMsg+=' and min-ht set';}
parent.setAttribute('data-ezoic-incontent-sticky',dataMsg);}
var overX=computedStyle.overflowX;if(['hidden','scroll','auto'].includes(overX)){overflowClass="clip";if(['scroll','auto'].includes(overX)){overflowClass="visible";}
this.adjustOverflowProperty(parent,ad_div,'overflow-x',overflowClass);}
if(parent.nodeType===1&&parent.tagName&&parent.tagName.toLowerCase()==='body'){break;}
parent=parent.parentElement;}}
var timeOut=3000;if(document.readyState==='complete'){timeOut=1000;}
setTimeout(function(){__ez.fads.incontentSticky.checkTopFixed();},timeOut);if(retry){setTimeout(function(){__ez.fads.incontentSticky.CheckIncontentSticky(false);},3000);}}catch(error){}}};} catch(err) {var hREED = function(er) {return function() {reportEzError(er, "/porpoiseant/ezicsticky.js")}}; typeof reportEzError==="function"?hREED(err):window.addEventListener('reportEzErrorDefined',hREED(err), {once: true}); console.error(err);}