try { __ez.fads.scrollMonitor={monitorCount:0,yLog:[],scrollDelta:0,totalScrollDelta:0,viewportHeight:0,documentHeight:0,loadAdFunctions:[],scrollPollingFrequency:200,adLoadedCallCount:0,loaded:true,incontentStickyCheck:false,viewportBottom:0,beenLoadedForLongEnough:false,mobileScalingFactor:1.2,additionalViewPortToload:0.5,latestAdLoadBounds:{},version:1,log:__ez.fads.log,init:function(viewportHeight,documentHeight,version){this.setViewportHeight(viewportHeight);this.setDocumentHeight(documentHeight);this.version=version;document.addEventListener('wheel',this.scrollWheelMonitor.bind(this));document.addEventListener('touchstart',this.scrollTouchMonitor.bind(this));this.monitorScroll(true);},reset:function(){this.monitorCount=0;this.yLog=[];this.scrollDelta=0;this.totalScrollDelta=0;this.loadAdFunctions=[];this.adLoadedCallCount=0;this.incontentStickyCheck=false;this.beenLoadedForLongEnough=false;},setViewportHeight:function(viewportHeight){this.viewportHeight=viewportHeight;__ez.fads.SetViewportHeight(viewportHeight);},setDocumentHeight:function(documentHeight){this.documentHeight=documentHeight;__ez.fads.SetDocumentHeight(documentHeight);},SetAdLoadFunctions:function(loadAdFunctions){if(typeof loadAdFunctions=='function'){loadAdFunctions=[loadAdFunctions];}
this.loadAdFunctions=loadAdFunctions;},GetScrollYPosition:function(){return Math.max(window.pageYOffset,document.documentElement.scrollTop,document.body.parentNode.scrollTop,document.body.scrollTop,this.totalScrollDelta);},isReady:function(){if(document.body!==null&&document.readyState!="loading"){return true;}
return false;},isFastAdsLoaded:function(){if(typeof __ez!='undefined'&&typeof __ez.fads!='undefined'){return true;}
return false;},detectDivPositions:function(){__ez.fads.callLibrary("positionMonitor","detectAdPositions",[]);},scrollWheelMonitor:function(e){this.scrollDelta=e.deltaY;this.totalScrollDelta+=e.deltaY;},scrollTouchMonitor:function(e){var delta=0;var startY=e.touches[0].pageY;var handleTouchMove=function(e){var currY=e.touches[0].pageY;delta+=startY-currY;startY=currY;}.bind(this);var handleTouchEnd=function(e){document.removeEventListener('touchmove',handleTouchMove);document.removeEventListener('touchend',handleTouchEnd);this.scrollDelta=delta;this.totalScrollDelta+=delta;}.bind(this);document.addEventListener('touchmove',handleTouchMove);document.addEventListener('touchend',handleTouchEnd);},monitorScroll:function(force){var sy=this.GetScrollYPosition();if(sy>250&&!this.incontentStickyCheck){this.incontentStickyCheck=true;__ez.fads.callLibrary("incontentSticky","CheckIncontentSticky");setTimeout(function(){__ez.fads.callLibrary("incontentSticky","CheckIncontentSticky");},500);}
if(sy>250&&typeof window.__eztopscrollanchor!=='undefined'&&window.__eztopscrollanchor===true){window.__eztopscrollanchor=false;__ez.fads.showScrollAnchor();}
var isShortPage=this.documentHeight<=(this.viewportHeight+100);this.viewportBottom=(this.viewportHeight+sy);var botThresh=this.viewportBottom+this.viewportHeight;if(this.scrollDelta==0&&this.isReady()){if(this.yLog.length>=10||this.last_sy!=0||sy<500){this.scrollDelta=sy-this.last_sy;}}
this.last_sy=sy;if(force===true||this.isReady()&&(this.scrollDelta!=0||(this.monitorCount<30&&sy!=0&&this.getTimeSinceLoad()<7000&&(isShortPage||(this.monitorCount>3&&this.yLog[3]==this.yLog[this.yLog.length-1]))))){this.logYPos(this.viewportBottom);var forceDetect=false;if(this.adLoadedCallCount==0){forceDetect=true;}
this.detectDivPositions(forceDetect,force);if(force&&__ez.fads.positionMonitor.loaded!=true){setTimeout(function(){__ez.fads.scrollMonitor.monitorScroll(true)},150);return;}
this.callLoadAdFunctions(this.CalculateAdLoadBounds(this.scrollDelta),false);this.scrollDelta=0;}else{this.logYPos(this.viewportBottom);}
setTimeout(this.monitorScroll.bind(this),this.scrollPollingFrequency);},callLoadAdFunctions:function(adLoadBounds,force){this.adLoadedCallCount++;for(var i=0;i<this.loadAdFunctions.length;i++){this.loadAdFunctions[i].call(__ez.fad,adLoadBounds,force);}},logYPos:function(bot){if(this.isReady()){this.monitorCount++;if(this.monitorCount%3==0){this.yLog.push(bot);if(this.yLog.length>50){this.yLog=this.yLog.slice(-30);this.monitorCount=30;}}}},PredictFutureScrolling:function(n=2){var y_log=this.getScrollTrend(this.yLog);const lastValues=y_log.slice(-12);if(lastValues.length<2){return[];}
let sumW=0,sumWX=0,sumWY=0,sumWXY=0,sumWX2=0;for(let i=0;i<lastValues.length;i++){const x=i;const y=Math.log(lastValues[i]);const w=i+1;sumW+=w;sumWX+=w*x;sumWY+=w*y;sumWXY+=w*x*y;sumWX2+=w*x*x;}
const m=(sumW*sumWXY-sumWX*sumWY)/(sumW*sumWX2-sumWX*sumWX);const c=(sumWY-m*sumWX)/sumW;const predictions=[];for(let i=1;i<=n;i++){const x_pred=lastValues.length+i-1;const y_pred_log=m*x_pred+c;predictions.push(Math.exp(y_pred_log));}
return predictions;},GetScrollDirection:function(scrollData){var last_pos=Math.round(scrollData[scrollData.length-1]);if(last_pos<this.viewportBottom){return "up";}else{return "down";}},getTimeSinceLoad:function(force){var longEnoughThreshold=7000;if(this.beenLoadedForLongEnough&&force!==true){return longEnoughThreshold;}
var diff=new Date().getTime()-__ez.fads.loadTime;if(diff>longEnoughThreshold){this.beenLoadedForLongEnough=true;}
return diff;},CalculateAdLoadBounds:function(scrollDelta){scrollDelta=scrollDelta||0;var vp_top=this.viewportBottom-this.viewportHeight;var top_bound=vp_top;var bottom_bound=this.viewportBottom;var external_top_bound=top_bound;var external_bottom_bound=bottom_bound;var predicted_scrolls=this.PredictFutureScrolling();var extra_vp=(this.viewportHeight*this.additionalViewPortToload);var external_extra_vp=this.viewportHeight*5;var ff=this.getFormFactor();var scaling=1;if(ff==2){scaling=this.mobileScalingFactor;}
var scrollingDirection=this.GetScrollDirection(predicted_scrolls);if(this.IsValidPredictedScroll(predicted_scrolls)){var last_pos=Math.round(predicted_scrolls[predicted_scrolls.length-1]);if(last_pos<this.viewportHeight){last_pos=this.viewportHeight;}
if(scrollingDirection=="up"){top_bound=last_pos-this.viewportHeight-extra_vp;external_top_bound=top_bound-(top_bound-last_pos);}else{bottom_bound=last_pos+extra_vp;external_bottom_bound=bottom_bound+(bottom_bound-this.viewportBottom);}}else{if(scrollingDirection=="up"){top_bound=vp_top+scrollDelta-extra_vp;external_top_bound=top_bound+scrollDelta-extra_vp;bottom_bound=this.viewportBottom;}else{bottom_bound=this.viewportBottom+scrollDelta+extra_vp;external_bottom_bound=bottom_bound+scrollDelta+extra_vp;top_bound=vp_top;}}
if(scrollingDirection=="up"){external_top_bound=external_top_bound-external_extra_vp;}else{external_bottom_bound=external_bottom_bound+external_extra_vp;}
if(scaling>1){if(scrollingDirection=="up"){top_bound=top_bound+((scrollDelta-extra_vp)*(scaling-1));external_top_bound=top_bound-((top_bound-last_pos)*(scaling-1));}else{bottom_bound=bottom_bound+((scrollDelta+extra_vp)*(scaling-1));external_bottom_bound=bottom_bound+((bottom_bound-this.viewportBottom)*(scaling-1));}}
if(top_bound<0||isNaN(top_bound)){top_bound=0;}
if(external_top_bound<0||isNaN(external_top_bound)){external_top_bound=0;}
if(bottom_bound<1200||isNaN(bottom_bound)){bottom_bound=1200;}
if(external_bottom_bound<1200||isNaN(external_bottom_bound)){external_bottom_bound=1200;}
this.latestAdLoadBounds={top_bound:top_bound,bottom_bound:bottom_bound,external_top_bound:external_top_bound,external_bottom_bound:external_bottom_bound}
return this.latestAdLoadBounds;},GetAdLoadBounds:function(){return this.latestAdLoadBounds;},IsValidPredictedScroll:function(predicted_scrolls){if(!Array.isArray(predicted_scrolls)){return false;}
if(predicted_scrolls.length<2){return false;}
for(let value of predicted_scrolls){if(typeof value!=='number'){return false;}}
return true;},getScrollTrend:function(y_log){if(y_log.length<2){return y_log;}
let trend=y_log[y_log.length-1]-y_log[y_log.length-2];let startIndex=y_log.length-2;for(let i=y_log.length-2;i>0;i--){let currentDiff=y_log[i]-y_log[i-1];if(Math.sign(currentDiff)!==Math.sign(trend)||Math.sign(currentDiff)==0){startIndex=i;break;}}
return y_log.slice(startIndex);},getFormFactor:function(){if(typeof window.ezoFormfactor!='undefined'){return window.ezoFormfactor;}
if(this.vw<768){return 2;}else{return 1;}},};} catch(err) {var hREED = function(er) {return function() {reportEzError(er, "/porpoiseant/ezjitscroll.js")}}; typeof reportEzError==="function"?hREED(err):window.addEventListener('reportEzErrorDefined',hREED(err), {once: true}); console.error(err);}